---
stages:
  - test
  - deploy

# Jobs defined  below
Syntax Check:
  stage: test
  script:
    - scripts/syntax_check.sh

# NOTE: The playground branches are intended for individuals to develop their
# changes.  Any branch starting with "playground" will automatically deploy to
# the puppetservers when pushed to the upstream repository.
Deploy to Puppet A:
  stage: deploy
  variables:
    SITE: A
  only:
    - production
    - /^playground/
  script:
    - scripts/puppet_deploy.sh

# Remove `when: manual` once Site B is online and names resolve.
Deploy to Puppet B:
  stage: deploy
  when: manual
  variables:
    SITE: B
  only:
    - production
    - /^playground/
  script:
    - scripts/puppet_deploy.sh

# vim:tabstop=2
# vim:shiftwidth=2
# vim:expandtab
